# Generated by Django 4.0.2 on 2023-03-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_time', models.DateTimeField()),
                ('note_content', models.CharField(max_length=200)),
                ('note_done', models.BooleanField()),
                ('noteList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes_app.notelist')),
            ],
        ),
    ]
